name: filters
description: A simple command-line app for creating cartoon filtered images.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  image:
  ml_linalg: '12.17.3'
  binary:
